# Generated by Django 4.2.3 on 2023-08-08 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0003_alter_libro_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
