# Generated by Django 4.2.3 on 2023-08-11 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0004_alter_libro_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='file',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
