# Generated by Django 4.2.3 on 2023-08-11 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0005_libro_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='file',
            field=models.FileField(blank=True, upload_to='media/'),
        ),
    ]
