# Generated by Django 4.2.3 on 2023-08-11 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0006_alter_libro_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='info',
            field=models.CharField(max_length=1000),
        ),
    ]
